# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Firebase/Core'

target 'firebasereact2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebasereact2

  target 'firebasereact2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'firebasereact2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firebasereact2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebasereact2-tvOS

  target 'firebasereact2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
